### ISSUE TITLE
Having problems with installation

### ISSUE THREAD

**Issue by vtomole** [rigetticomputing/oqaml#7] opened 2017-09-16 16:02 UTC
This is what I get: https://pastebin.com/qceDWNkg

(edit for readability)
```
vtomole@vtomole:~/oqaml$ sudo make all && make install
ocaml setup.ml -build -tag thread
Start compiling OQaml ...
+ ocamlfind ocamlopt unix.cmxa -I /home/vtomole/.opam/4.04.2/lib/ocamlbuild /home/vtomole/.opam/4.04.2/lib/ocamlbuild/ocamlbuildlib.cmxa -linkpkg myocamlbuild.ml /home/vtomole/.opam/4.04.2/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
File "myocamlbuild.ml", line 1:
Error: /home/vtomole/.opam/4.04.2/lib/ocamlbuild/ocamlbuild_plugin.cmi
is not a compiled interface for this version of OCaml.
It seems to be for a newer version of OCaml.
Command exited with code 2.
Compilation unsuccessful after building 1 target (0 cached) in 00:00:00.
E: Failure("Command ''/home/vtomole/.opam/4.04.2/bin/ocamlbuild' src/oqaml.cma src/oqaml.cmxa src/oqaml.a src/oqaml.cmxs -use-ocamlfind -tag debug -tag thread' terminated with error code 10")
Makefile:25: recipe for target 'all' failed
make: *** [all] Error 1
```

**Comment by jotterbach** [comment] 2017-09-17 03:33
Hi @vtomole . I haven't seen this error before. Quick googling indicated that your Ocaml environment might be stale (https://ocaml.org/learn/tutorials/common_error_messages.html#x-cmi-is-not-a-compiled-interface).

`ocamlbuild` is part of the Ocaml standard library and not of OQaml, so maybe your Ocaml environment needs to be cleaned?

**Comment by vtomole** [comment] 2017-09-17 03:49
After I  ```sudo rm /home/vtomole/.opam/4.04.2/lib/ocamlbuild/ocamlbuild_plugin.cmi```, I now get:
```ocaml setup.ml -build -tag thread
Start compiling OQaml ...
Exception Sys_error("/home/vtomole/oqaml/_build/_log: Permission denied").
E: Failure("Command ''/home/vtomole/.opam/4.04.2/bin/ocamlbuild' src/oqaml.cma src/oqaml.cmxa src/oqaml.a src/oqaml.cmxs -use-ocamlfind -tag debug -tag thread' terminated with error code 100")
Makefile:27: recipe for target 'install' failed
make: *** [install] Error 1
```
I'm new to OCaml. So I don't know how to clean up the environment.

**Comment by jotterbach** [comment] 2017-09-17 05:28
Hmm. It still seems that your build environment is stale or misconfigured. Can you try to reinstall `ocamlbuild`? Something like `opam remove ocamlbuild` followed by `opam install ocamlbuild`.

It could be in the end that you need to completely set up your Ocaml environment again; problems in the environment are hard to debug like this.  Alternatively you could take a look at the `Dockerfile` and `semaphore_test.sh` to see how the testing environments are set up.

How did you set up your environment and which OS are you using?

**Comment by vtomole** [comment] 2017-09-17 07:27
I did ```sudo make && sudo make install``` and that error is now gone. now I get 
```vtomole@vtomole:~/oqaml$ sudo make all && sudo make install
jbuilder build @install
make: jbuilder: Command not found
Makefile:19: recipe for target 'all' failed
make: *** [all] Error 127
```
I'm guessing it's because I'm trying to run jbuilder with sudo?

**Comment by jotterbach** [comment] 2017-09-17 19:51
did you install `jbuilder` ? Try `opam install jbuilder` and then the regular install again. But in general you shouldn't have to run with sudo.

**Comment by vtomole** [comment] 2017-09-17 20:02
Yes jbuilder is installed. I'm going to try out the installation on a VM. See how it works out.

**Comment by vtomole** [comment] 2017-09-18 22:11
I got it running on the owl docker instance
```utop # #require "oqaml";; ``` gives me 
```Error: Reference to undefined global `Owl_dense_matrix' ```

**Comment by jotterbach** [comment] 2017-09-18 22:35
Awesome! I tried to reproduce your issue on a fresh docker build but I am unable to get this error. Can you copy and paste your Docker code and the step you use for setting it up? For comparison here is what I did:

1. in the OQaml folder I run: `docker build . -t "rigetticomputing/oqaml"`
2. then I start the container (in the same folder): `docker run -v $(pwd):/root/oqaml -it rigetticomputing/oqaml /bin/bash`. This drops be as the docker root into the owl folder.
3. in the docker container I switch to the oqaml folder: `cd /root/oqaml`
4. i build the files by running `make all`
5. i install the code by running `make install`
6. i start utop and import all the dependencies

this recipe worked for me.

**Comment by vtomole** [comment] 2017-09-19 02:31
I deleted the oqaml repo, re-cloned, ``git checkout 9fabba95``, followed what you did and got the same error. I think I figured out why I was getting the jbuilder error. Maybe it was because I was using the wrong compiler version.
```root@f81097324dbe:~/oqaml# ocaml --version
The OCaml toplevel, version 4.04.2
root@f81097324dbe:~/oqaml# make all && make install
jbuilder build @install
make: jbuilder: Command not found
Makefile:19: recipe for target 'all' failed
make: *** [all] Error 127
root@f81097324dbe:~/oqaml# make all                
jbuilder build @install
make: jbuilder: Command not found
Makefile:19: recipe for target 'all' failed
make: *** [all] Error 127
root@f81097324dbe:~/oqaml# opam switch 4.04.0
[WARNING] Running as root is not recommended
# To setup the new switch in the current shell, you need to run:
eval `opam config env`
root@f81097324dbe:~/oqaml# eval `opam config env`
[WARNING] Running as root is not recommended
root@f81097324dbe:~/oqaml# ocaml --version
The OCaml toplevel, version 4.04.0
root@f81097324dbe:~/oqaml# make all 
jbuilder build @install
root@f81097324dbe:~/oqaml# make install
jbuilder install
        opam (internal)
[WARNING] Running as root is not recommended
opam-installer oqaml.install
_build/install/default/lib/oqaml/META => /root/.opam/4.04.0/lib/oqaml/META
_build/install/default/lib/oqaml/opam => /root/.opam/4.04.0/lib/oqaml/opam
_build/install/default/lib/oqaml/oqaml.cmi => /root/.opam/4.04.0/lib/oqaml/oqaml.cmi
_build/install/default/lib/oqaml/oqaml.cmx => /root/.opam/4.04.0/lib/oqaml/oqaml.cmx
_build/install/default/lib/oqaml/oqaml.cmt => /root/.opam/4.04.0/lib/oqaml/oqaml.cmt
_build/install/default/lib/oqaml/oqaml.cmti => /root/.opam/4.04.0/lib/oqaml/oqaml.cmti
_build/install/default/lib/oqaml/oqaml.mli => /root/.opam/4.04.0/lib/oqaml/oqaml.mli
_build/install/default/lib/oqaml/primitives.cmi => /root/.opam/4.04.0/lib/oqaml/primitives.cmi
_build/install/default/lib/oqaml/primitives.cmx => /root/.opam/4.04.0/lib/oqaml/primitives.cmx
_build/install/default/lib/oqaml/primitives.cmt => /root/.opam/4.04.0/lib/oqaml/primitives.cmt
_build/install/default/lib/oqaml/primitives.cmti => /root/.opam/4.04.0/lib/oqaml/primitives.cmti
_build/install/default/lib/oqaml/primitives.mli => /root/.opam/4.04.0/lib/oqaml/primitives.mli
_build/install/default/lib/oqaml/utils.cmi => /root/.opam/4.04.0/lib/oqaml/utils.cmi
_build/install/default/lib/oqaml/utils.cmx => /root/.opam/4.04.0/lib/oqaml/utils.cmx
_build/install/default/lib/oqaml/utils.cmt => /root/.opam/4.04.0/lib/oqaml/utils.cmt
_build/install/default/lib/oqaml/utils.cmti => /root/.opam/4.04.0/lib/oqaml/utils.cmti
_build/install/default/lib/oqaml/utils.mli => /root/.opam/4.04.0/lib/oqaml/utils.mli
_build/install/default/lib/oqaml/oqaml.cma => /root/.opam/4.04.0/lib/oqaml/oqaml.cma
_build/install/default/lib/oqaml/oqaml.cmxa => /root/.opam/4.04.0/lib/oqaml/oqaml.cmxa
_build/install/default/lib/oqaml/oqaml.a => /root/.opam/4.04.0/lib/oqaml/oqaml.a
_build/install/default/lib/oqaml/oqaml.cmxs => /root/.opam/4.04.0/lib/oqaml/oqaml.cmxs
_build/install/default/doc/oqaml/README.md => /root/.opam/4.04.0/doc/oqaml/README.md
_build/install/default/doc/oqaml/LICENSE => /root/.opam/4.04.0/doc/oqaml/LICENSE
```

**Comment by jotterbach** [comment] 2017-09-19 03:26
It's confusing to me why your toplevel is version `4.04.2` but yes, that could be the reason for why all this fails. Does it work now that you changed the toplevel version?

Just for completion. Running `jbuilder installed-libraries` inside the Docker container gives me:

```
alcotest                            (version: 0.7.2)
astring                             (version: 0.8.3)
astring.top                         (version: 0.8.3)
atd                                 (version: v1.12.0)
atdgen                              (version: v1.12.0)
base                                (version: v0.9.3)
base.caml                           (version: v0.9.3)
base.shadow_stdlib                  (version: v0.9.3)
bigarray                            (version: [distributed with Ocaml])
bin_prot                            (version: v0.9.1)
bin_prot.shape                      (version: v0.9.1)
biniou                              (version: 1.2.0)
bytes                               (version: [distributed with OCaml 4.02 or above])
camlp4                              (version: [distributed with Ocaml])
camlp4.exceptiontracer              (version: [distributed with Ocaml])
camlp4.extend                       (version: [distributed with Ocaml])
camlp4.foldgenerator                (version: [distributed with Ocaml])
camlp4.fulllib                      (version: [distributed with Ocaml])
camlp4.gramlib                      (version: [distributed with Ocaml])
camlp4.lib                          (version: [distributed with Ocaml])
camlp4.listcomprehension            (version: [distributed with Ocaml])
camlp4.locationstripper             (version: [distributed with Ocaml])
camlp4.macro                        (version: [distributed with Ocaml])
camlp4.mapgenerator                 (version: [distributed with Ocaml])
camlp4.metagenerator                (version: [distributed with Ocaml])
camlp4.profiler                     (version: [distributed with Ocaml])
camlp4.quotations                   (version: [distributed with Ocaml])
camlp4.quotations.o                 (version: [distributed with Ocaml])
camlp4.quotations.r                 (version: [distributed with Ocaml])
camlp4.tracer                       (version: [distributed with Ocaml])
camomile                            (version: 0.8.5)
cmdliner                            (version: 0.9.8)
compiler-libs                       (version: [distributed with Ocaml])
compiler-libs.bytecomp              (version: [distributed with Ocaml])
compiler-libs.common                (version: [distributed with Ocaml])
compiler-libs.optcomp               (version: [distributed with Ocaml])
compiler-libs.toplevel              (version: [distributed with Ocaml])
configurator                        (version: v0.9.1)
core                                (version: v0.9.1)
core.syntax                         (version: [deprecated])
core.top                            (version: v0.9.1)
core_extended                       (version: v0.9.0)
core_extended.base64                (version: v0.9.0)
core_extended.selection             (version: v0.9.0)
core_kernel                         (version: v0.9.0)
core_kernel.base_for_tests          (version: v0.9.0)
cppo_ocamlbuild                     (version: 1.4.1)
ctypes                              (version: 0.11.1)
ctypes.stubs                        (version: 0.11.1)
ctypes.top                          (version: 0.11.1)
dolog                               (version: 0.3)
dynlink                             (version: [distributed with Ocaml])
easy-format                         (version: n/a)
eigen                               (version: 0.1)
fieldslib                           (version: v0.9.0)
findlib                             (version: 1.7.1)
findlib.dynload                     (version: 1.7.1)
fmt                                 (version: 0.8.0)
fmt.cli                             (version: 0.8.0)
fmt.top                             (version: 0.8.0)
fmt.tty                             (version: 0.8.0)
graphics                            (version: [distributed with Ocaml])
gsl                                 (version: 1.19.1)
jane-street-headers                 (version: v0.9.0)
jbuilder                            (version: n/a)
lacaml                              (version: 9.1.1)
lacaml.top                          (version: 9.1.1)
lambda-term                         (version: 1.10.1)
lwt                                 (version: 2.6.0)
lwt.log                             (version: 2.6.0)
lwt.ppx                             (version: 2.6.0)
lwt.preemptive                      (version: 2.6.0)
lwt.react                           (version: 2.6.0)
lwt.simple-top                      (version: 2.6.0)
lwt.unix                            (version: 2.6.0)
menhirLib                           (version: n/a)
menhirSdk                           (version: n/a)
num                                 (version: [distributed with Ocaml])
num-top                             (version: 1.7.1)
num.core                            (version: [internal])
oasis                               (version: 0.4.8)
oasis.base                          (version: 0.4.8)
oasis.builtin-plugins               (version: 0.4.8)
oasis.cli                           (version: 0.4.8)
oasis.dynrun                        (version: 0.4.8)
ocaml-compiler-libs                 (version: n/a)
ocaml-compiler-libs.bytecomp        (version: v0.9.0)
ocaml-compiler-libs.common          (version: v0.9.0)
ocaml-compiler-libs.shadow          (version: v0.9.0)
ocaml-compiler-libs.toplevel        (version: v0.9.0)
ocaml-migrate-parsetree             (version: n/a)
ocaml-migrate-parsetree.driver-main (version: n/a)
ocamlbuild                          (version: 0.9.3)
ocamldoc                            (version: [distributed with Ocaml])
octavius                            (version: 1.1.0)
owl                                 (version: 0.1)
owl_zoo                             (version: 0.1)
plplot                              (version: 5.11.0)
plugin-loader                       (version: 0.4.8)
ppx_assert                          (version: v0.9.0)
ppx_assert.runtime-lib              (version: v0.9.0)
ppx_ast                             (version: v0.9.1)
ppx_base                            (version: v0.9.0)
ppx_bench                           (version: v0.9.1)
ppx_bench.runtime-lib               (version: v0.9.1)
ppx_bin_prot                        (version: v0.9.0)
ppx_bin_prot.shape-expander         (version: v0.9.0)
ppx_compare                         (version: v0.9.0)
ppx_compare.expander                (version: v0.9.0)
ppx_compare.runtime-lib             (version: v0.9.0)
ppx_core                            (version: v0.9.0)
ppx_custom_printf                   (version: v0.9.0)
ppx_driver                          (version: v0.9.1)
ppx_driver.ocamlbuild               (version: v0.9.1)
ppx_driver.print_diff               (version: v0.9.1)
ppx_driver.runner                   (version: v0.9.1)
ppx_driver.runner_as_ppx            (version: v0.9.1)
ppx_enumerate                       (version: v0.9.0)
ppx_expect                          (version: v0.9.0)
ppx_expect.collector                (version: v0.9.0)
ppx_expect.common                   (version: v0.9.0)
ppx_expect.config                   (version: v0.9.0)
ppx_expect.evaluator                (version: v0.9.0)
ppx_expect.matcher                  (version: v0.9.0)
ppx_expect.payload                  (version: v0.9.0)
ppx_fail                            (version: v0.9.0)
ppx_fields_conv                     (version: v0.9.0)
ppx_hash                            (version: v0.9.0)
ppx_hash.expander                   (version: v0.9.0)
ppx_hash.runtime-lib                (version: v0.9.0)
ppx_here                            (version: v0.9.1)
ppx_here.expander                   (version: v0.9.1)
ppx_inline_test                     (version: v0.9.2)
ppx_inline_test.config              (version: v0.9.2)
ppx_inline_test.drop                (version: v0.9.2)
ppx_inline_test.libname             (version: v0.9.2)
ppx_inline_test.runner              (version: v0.9.2)
ppx_inline_test.runner.lib          (version: v0.9.2)
ppx_inline_test.runtime-lib         (version: v0.9.2)
ppx_jane                            (version: v0.9.0)
ppx_jane.kernel                     (version: v0.9.0)
ppx_js_style                        (version: v0.9.0)
ppx_let                             (version: v0.9.0)
ppx_metaquot                        (version: v0.9.0)
ppx_metaquot.lifters                (version: v0.9.0)
ppx_optcomp                         (version: v0.9.0)
ppx_optional                        (version: v0.9.0)
ppx_pipebang                        (version: v0.9.0)
ppx_sexp_conv                       (version: v0.9.0)
ppx_sexp_conv.expander              (version: v0.9.0)
ppx_sexp_message                    (version: v0.9.0)
ppx_sexp_value                      (version: v0.9.0)
ppx_tools                           (version: 5.0)
ppx_tools.metaquot                  (version: 5.0)
ppx_traverse                        (version: v0.9.0)
ppx_traverse_builtins               (version: v0.9.0)
ppx_type_conv                       (version: v0.9.0)
ppx_typerep_conv                    (version: v0.9.0)
ppx_variants_conv                   (version: v0.9.0)
raw_spacetime                       (version: [distributed with Ocaml])
re                                  (version: 1.7.1)
re.emacs                            (version: 1.7.1)
re.glob                             (version: 1.7.1)
re.pcre                             (version: 1.7.1)
re.perl                             (version: 1.7.1)
re.posix                            (version: 1.7.1)
re.str                              (version: 1.7.1)
re2                                 (version: v0.9.0)
re2.c                               (version: v0.9.0)
react                               (version: 1.2.0)
react.top                           (version: 1.2.0)
result                              (version: 1.0)
sexplib                             (version: v0.9.2)
sexplib.0                           (version: v0.9.2)
sexplib.num                         (version: v0.9.2)
sexplib.unix                        (version: v0.9.2)
spawn                               (version: v0.9.0)
stdio                               (version: v0.9.0)
stdlib                              (version: [distributed with Ocaml])
str                                 (version: [distributed with Ocaml])
textutils                           (version: v0.9.0)
threads                             (version: [distributed with Ocaml])
threads.posix                       (version: [internal])
threads.vm                          (version: [internal])
topkg                               (version: 0.8.1)
typerep                             (version: v0.9.0)
unix                                (version: [distributed with Ocaml])
utop                                (version: 1.19.3)
variantslib                         (version: v0.9.0)
yojson                              (version: 1.4.0)
yojson.biniou                       (version: n/a)
zed                                 (version: 1.4)
```

and after installing OQaml I have an additional entry:
```
...
ocamldoc                            (version: [distributed with Ocaml])
octavius                            (version: 1.1.0)
oqaml                               (version: 0.0.1)
owl                                 (version: 0.1)
owl_zoo                             (version: 0.1)
...
```

**Comment by vtomole** [comment] 2017-09-19 03:40
I switched it to 4.04.2 cause that is what I read here: https://github.com/rigetticomputing/oqaml/blob/master/readmes/oqaml_setup.md

Here are the differences between my jbuilder installed-libraries and yours
Mine:
```	owl (version: dev)		
	owl_zoo (version: dev)
```

Yours
```owl (version: 0.1)
owl_zoo  (version: 0.1)```

**Comment by jotterbach** [comment] 2017-09-19 05:45
hmm ... that might hint to a problem. Owl recently introduced several breaking changes that we haven't tested throughly yet. I didn't expect it to break everything though. Can you pin the Owl dependency just in case?

**Comment by jotterbach** [comment] 2017-09-19 05:52
In fact I just tested it with the current master head of `Owl` and its not breaking. The expected `pretty_print` functionality changed, but I can still import all functions and work with it.

**Comment by vtomole** [comment] 2017-09-19 05:53
Is that ```root@7ceaaa43b584:~# opam pin add owl 1.1
[WARNING] Running as root is not recommended
[ERROR] Package owl has no version 1.1
``?

**Comment by jotterbach** [comment] 2017-09-19 05:55
you mean `opam pin add owl 0.1` instead of `1.1`?

**Comment by vtomole** [comment] 2017-09-19 05:57
Ah. Yes, typo.

**Comment by vtomole** [comment] 2017-09-19 05:58
[ERROR] Package owl has no version 0.1. I'm using ubuntu 16.04 btw.

**Comment by jotterbach** [comment] 2017-09-19 06:03
What's the docker file you use? If you follow the exact steps that I outlined above with the [Dockerfile from this repo](https://github.com/rigetticomputing/oqaml/blob/master/Dockerfile) forking from `ryanryhmes/owl`, what happens?

**Comment by vtomole** [comment] 2017-09-19 06:18
Yeah. The exact steps with the dockerfile in the oqaml directory. I just did the same thing on a VM (also ubuntu 16.04) and I got the same error.
```utop # #require "oqaml";;
Error: Reference to undefined global `Owl_dense_matrix' ```

**Comment by vtomole** [comment] 2017-09-19 06:22
The full thing: https://gist.github.com/vtomole/21a295575be9cf4b135e03c7beaad0f4

**Comment by jotterbach** [comment] 2017-09-19 06:47
I'm starting to run out of ideas here as I cannot reproduce this failure. I just tested the above instructions on a fresh linux ubuntu 16.04 image. It worked. I remember seeing this kind of issue when the compiled version of OQaml was built against an old version of Owl. Can you clean all your OQaml build files and build it again in the Docker container? 

1. in the OQaml repo: `git clean -fdx`
2. build the docker container (ensure no cache): `docker build . -t "rigetticomputing/oqaml --no-cache"
3. start the container (in the same folder): `docker run -v $(pwd):/root/oqaml -it rigetticomputing/oqaml /bin/bash`.
4. switch to the oqaml folder: `cd /root/oqaml`
5. build the files by running `make all`
6. install the code by running `make install`
7. start utop and import all the dependencies

I think the key is to control all steps in your local builds. Maybe you can post a complete copy of a Dockerfile that I can run locally to reproduce the error?

**Comment by vtomole** [comment] 2017-09-20 15:15
I have no idea either. I installed another vm and I'm still getting ```Error: Reference to undefined global `Owl_dense_matrix'``` when I ``#require "oqaml```.

Is there anyway you can share the image file you used that it worked on?

**Comment by vtomole** [comment] 2017-09-20 15:36
In new VM (ubuntu 16.04)
1. ```sudo apt-get install git```
2. ```https://github.com/rigetticomputing/oqaml.git```
3.  ```cd oqaml/```
4. ```sudo apt install docker.io```
5. ```sudo docker build . -t "rigetticomputing/oqaml"```
6.  ```sudo docker run -v $(pwd):/root/oqaml -it rigetticomputing/oqaml /bin/bash```
7.  ```root@6aad0312f4ca:~/owl# cd /root/oqaml/```
8.  ```root@6aad0312f4ca:~/oqaml# make all ```
9.  ```root@6aad0312f4ca:~/oqaml# make install```
10. ```root@6aad0312f4ca:~/oqaml# utop ```
11. ```utop # #require "oqaml";;``` => ```Error: Reference to undefined global `Owl_dense_matrix' ```

**Comment by jotterbach** [comment] 2017-09-20 15:58
Hmm. One difference I spot is that you build and run the docker container as sudo. I wonder if that results in the container having no access to the shared library directories as the permissions might be wonky. Otherwise it looks similar to what I did. 

Docker in fact encourages you to perform some post-docker install steps: https://docs.docker.com/engine/installation/linux/linux-postinstall/ that include adding your user to the docker group.

**Comment by vtomole** [comment] 2017-09-20 16:59
I ran sudo can I was getting ```Cannot connect to the Docker daemon. Is the docker daemon running on this host?```

**Comment by vtomole** [comment] 2017-09-20 17:13
I was able to add the docker group and do ``docker build``` and ``docker run`` without sudo and still ```Error: Reference to undefined global `Owl_dense_matrix'```. I'm going to run the same instructions with after ```git clean -fdx```.

I would be interested in running the .img you are using.

**Comment by vtomole** [comment] 2017-09-20 17:36
The new one: https://gist.github.com/vtomole/41ceb3479a9297df30e09265101b4790

**Comment by jotterbach** [comment] 2017-09-22 05:46
@vtomole I pushed a personal and hence not officially supported Docker image to https://hub.docker.com/r/jotterbach/oqaml/tags/

1. `docker pull jotterbach/oqaml`
2. `docker run -it jotterbach/oqaml`
3. `utop`

Hope this works.

**Comment by vtomole** [comment] 2017-09-22 05:57
It works! :smiley:

**Comment by jotterbach** [comment] 2017-09-22 06:25
For completeness. The commands I used to create the image are:

```
FROM ryanrhymes/owl

RUN opam install -y core_extended

RUN mkdir -p /root/oqaml

COPY . /root/oqaml

WORKDIR /root/oqaml
RUN make test
RUN make all
RUN make install

ENTRYPOINT "/bin/bash"
```

And I put this into a Dockerfile in my local OQaml folder. Building worked with `docker build . "jotterbach/oqaml"`.

@vtomole As you have a working version now, can I close this ticket?

**Comment by vtomole** [comment] 2017-09-22 06:26
Yes. Thank you.

**Comment by jotterbach** [comment] 2017-09-22 06:31
Awesome! Glad we could make this happen in the end!

**Closed as completed by jotterbach** 2017-09-22 06:31 UTC
